import { Link } from 'react-router-dom';
import { motion } from 'framer-motion';
import { Download, ArrowRight } from 'lucide-react';
import { SuccessCheck } from '../../motion/feedback.jsx';
import { formatMoney } from '../../data/touristVisas.js';

const fmtDate = (iso) => new Date(iso).toLocaleDateString(undefined, { day: '2-digit', month: 'long', year: 'numeric' });

export default function ApplicationConfirmationCard({ application }) {
  const p = application.payment || {};
  const hasPayment = Boolean(application.payment);
  const rows = [
    ['Application ID', application.id],
    ...(hasPayment
      ? [
          ['Payment reference', p.reference || '—'],
          ['Destination', application.countryName],
          ['Visa type', application.visaTypeLabel],
          ['Amount paid', p.amount ? formatMoney(p.amount, p.currency) : '—']
        ]
      : [
          ['Destination', application.countryName],
          ['Visa type', application.visaTypeLabel]
        ]),
    ['Date', p.paidAt ? fmtDate(p.paidAt) : fmtDate(application.updatedAt)]
  ];

  return (
    <motion.div className="confirm-card" initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.4 }}>
      <div className="confirm-card__icon">
        <SuccessCheck size={48} />
      </div>
      <h2>{hasPayment ? 'Payment successful — application submitted' : 'Application submitted'}</h2>
      <p className="confirm-card__lead">
        We've received your {application.countryName} tourist visa application. Our team will review
        your details and documents and contact you if anything else is needed.
      </p>

      <dl className="confirm-card__grid">
        {rows.map(([k, v]) => (
          <div key={k}>
            <dt>{k}</dt>
            <dd>{v}</dd>
          </div>
        ))}
      </dl>

      <div className="confirm-card__disclaimer">
        {hasPayment
          ? 'Payment confirms submission of your application. Visa approval is subject to the applicable immigration / visa authority and its verification process — it is not guaranteed by this payment.'
          : 'Submission of your application does not guarantee visa approval, which is subject to the applicable immigration / visa authority and its verification process.'}
      </div>

      <div className="confirm-card__actions">
        <Link to={`/application/${application.id}`} className="btn btn--coral btn--lg">
          View application status <ArrowRight aria-hidden="true" />
        </Link>
        <button type="button" className="btn btn--outline btn--lg" disabled title="The signed receipt is generated by the backend">
          <Download aria-hidden="true" /> Download receipt
        </button>
      </div>
      <p className="confirm-card__foot">
        A confirmation has been sent to <strong>{application.applicant.email}</strong>. Keep your
        application ID for reference.
      </p>
    </motion.div>
  );
}
